### ISSUE TITLE
Problem with the appearance of the players

### ISSUE THREAD

**Issue by Leeo97one** [iChun/Shatter#18]
Minecraft : 1.7.10
Forge : 10.13.0.1207
Shatter : 4.0.0
iChunUtil : 4.0.0

When a player suffers a death, the appearance of all the players becomes anything.
Invisible skin, a foot instead of an arm, etc...

**Comment by iChun** [comment]
This would be an issue with SmartMoving I'm afraid. Is this still occuring in the 1.8 versions though? A significant amount of model code was changed in those versions.

**Comment by iChun** [comment]
Due to the age of this issue (and that I no longer support my mods for 1.12.2 and older) I am closing this issue. My apologies we weren't able to work out a fix.

**Comment by Leeo97one** [comment]
No problem, thanks for your mods!

(And omg my English was so bad back then xD)

**Comment by Leeo97one** [comment]
Also, may I ask you to remove the "Pellet" name in your first reply (https://github.com/iChun/Shatter/issues/18#issuecomment-53416511)?
