### ISSUE TITLE
[1.7.10] [4.0.0] SMP shattered entities disappear

### ISSUE THREAD

**Issue by Fickilty** [iChun/Shatter#23]
Aproximately, when facing -80~80 degrees (SWW~SEE), shattered entities vanish. Changing the angle the player character is facing, and crossing said boundaries, will cause shattered entities to reappear and disappear.

**Comment by Fickilty** [comment]
The degree effect above^ also works with pitch, facing south and straight down the shattered entities render, Likewise facing straight up.

And now the reverse is true? Shattered entities won't render unless I face west? No. Okay. This is weird. That just changed again, first they were rendering when I faced Between W~N, and now they're rendering when I face any direction, inlcuding south.

Also: AHA. I also knew some entities weren't appearing at all. Zombie Villagers don't shatter either, they just vanish.

**Comment by iChun** [comment]
Due to the age of this issue (and that I no longer support my mods for 1.12.2 and older) I am closing this issue. My apologies we weren't able to work out a fix.
