### ISSUE TITLE
[1.12.2][7.0.0] Registering Texture NPE crash

### ISSUE THREAD

**Issue by Alaberti** [iChun/Shatter#25]
https://pastebin.com/9qQ9ZY8z

Not really sure what happened here, but the reporting player says they were only flying around near a Weather 2 tornado when this crash happened. If it's mob related, we have animania, vampirism, and deadly monsters mobs beyond vanilla.

**Comment by Alaberti** [comment]
Upon further investigation, it seems to be related to "nonstandard" deaths, but it happens so infrequently it's tough to pin down exact causes.

**Comment by iChun** [comment]
Nooooo don't close this, I might be able to fix it.
