### ISSUE TITLE
Crashes immediately when killing Custom Entity Models mobs

### ISSUE THREAD

**Issue by DerpTehTurtle** [iChun/Shatter#31]
I made my resourcepack with some Custom Entity Models and optifine to make the mobs looks a bit better but killing the mobs kills the game. My guess is that the mod can't handle the new parts of the mobs?

**Comment by iChun** [comment]
Without a crash log I can't say, but I reckon it's an Optifine thing.

**Comment by DerpTehTurtle** [comment]
EDIT: I didn't save my last crash report but I did end up experiencing it again with a zombie pig man
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 8/16/18 3:04 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.createCubeInfoFromModelBox(ModelHelper.java:111)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:154)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:187)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:187)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.getModelCubesCopy(ModelHelper.java:70)
	at me.ichun.mods.shatter.client.model.ModelShattered.<init>(ModelShattered.java:47)
	at me.ichun.mods.shatter.client.render.RenderShattered.doRender(RenderShattered.java:33)
	at me.ichun.mods.shatter.client.render.RenderShattered.func_76986_a(RenderShattered.java:14)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:823)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1918)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.createCubeInfoFromModelBox(ModelHelper.java:111)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:154)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:187)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.buildCopy(ModelHelper.java:187)
	at me.ichun.mods.ichunutil.client.model.util.ModelHelper.getModelCubesCopy(ModelHelper.java:70)
	at me.ichun.mods.shatter.client.model.ModelShattered.<init>(ModelShattered.java:47)
	at me.ichun.mods.shatter.client.render.RenderShattered.doRender(RenderShattered.java:33)
	at me.ichun.mods.shatter.client.render.RenderShattered.func_76986_a(RenderShattered.java:14)

-- Entity being rendered --
Details:
	Entity Type: null (me.ichun.mods.shatter.client.entity.EntityShattered)
	Entity ID: 839
	Entity Name: unknown
	Entity's Exact location: 32.20, 63.02, 130.51
	Entity's Block location: World: (32,63,130), Chunk: (at 0,3,2 in 2,8; contains blocks 32,0,128 to 47,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: me.ichun.mods.shatter.client.render.RenderShattered@20d8e860
	Location: 3.09,-0.82,0.08 - World: (3,-1,0), Chunk: (at 3,-1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 55.670307
	Delta: 0.61999416
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:823)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1918)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DerpTehTurtle'/473, l='MpServer', x=29.00, y=63.79, z=130.43]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (144,64,241), Chunk: (at 0,4,1 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1013160 game time, 1046982 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntityItem['item.item.rottenFlesh'/832, l='MpServer', x=31.72, y=63.28, z=130.34], EntityDeer['Deer'/129, l='MpServer', x=38.20, y=64.00, z=75.30], EntityVillager['Villager'/130, l='MpServer', x=40.89, y=64.00, z=84.47], EntitySpark['Spark'/131, l='MpServer', x=32.50, y=65.50, z=120.50], EntitySpark['Spark'/132, l='MpServer', x=41.50, y=64.50, z=124.50], EntityVillager['Villager'/133, l='MpServer', x=33.07, y=64.00, z=126.18], EntitySheep['Sheep'/134, l='MpServer', x=32.50, y=64.00, z=115.26], EntityPigZombie['Zombie Pigman'/135, l='MpServer', x=32.20, y=63.02, z=130.51], EntityShattered['unknown'/839, l='MpServer', x=32.20, y=63.02, z=130.51], EntityBat['Bat'/590, l='MpServer', x=-48.57, y=23.07, z=76.69], EntityCow['Cow'/145, l='MpServer', x=48.38, y=62.54, z=179.65], EntityCow['Cow'/146, l='MpServer', x=57.95, y=73.00, z=180.53], EntityChicken['Chicken'/212, l='MpServer', x=110.33, y=69.00, z=186.56], EntityWolf['Wolf'/213, l='MpServer', x=109.70, y=68.00, z=186.50], EntityChicken['Chicken'/214, l='MpServer', x=108.74, y=70.00, z=199.15], EntitySkeleton['Skeleton'/598, l='MpServer', x=-27.50, y=23.00, z=157.50], EntityCow['Cow'/152, l='MpServer', x=65.78, y=77.00, z=187.49], EntityCow['Cow'/153, l='MpServer', x=68.80, y=83.00, z=191.47], EntityCow['Cow'/154, l='MpServer', x=64.44, y=81.00, z=193.19], EntityPlayerSP['DerpTehTurtle'/473, l='MpServer', x=29.00, y=63.79, z=130.43], EntityLatchedRenderer['unknown'/542, l='MpServer', x=29.00, y=63.79, z=130.43], EntityDeer['Deer'/111, l='MpServer', x=16.21, y=63.00, z=73.18], EntityVillager['Villager'/112, l='MpServer', x=11.33, y=64.50, z=70.50], EntityDeer['Deer'/113, l='MpServer', x=5.21, y=62.55, z=98.94], EntityVillager['Villager'/114, l='MpServer', x=12.35, y=67.00, z=107.30], EntitySheep['Sheep'/115, l='MpServer', x=11.52, y=69.00, z=189.10], EntitySheep['Sheep'/116, l='MpServer', x=3.19, y=70.00, z=199.50], EntityVillager['Villager'/118, l='MpServer', x=15.49, y=63.00, z=78.50], EntityCow['Cow'/119, l='MpServer', x=30.60, y=64.00, z=111.19], EntityVillager['Villager'/120, l='MpServer', x=19.57, y=64.00, z=96.25], EntityPig['Pig'/121, l='MpServer', x=30.69, y=64.00, z=115.49], EntitySheep['Sheep'/122, l='MpServer', x=22.47, y=74.00, z=192.74], EntityCow['Cow'/187, l='MpServer', x=98.17, y=69.00, z=184.49], EntityChicken['Chicken'/188, l='MpServer', x=85.45, y=70.00, z=188.11]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1843894192 bytes (1758 MB) / 3724541952 bytes (3552 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.4.2750 Optifine OptiFine_1.12.2_HD_U_D1 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                  | Source                                          | Signature                                |
	|:--------- |:----------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.4.2750.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.4.2750             | forge-1.12.2-14.23.4.2750.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit               | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | movillages              | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                      | None                                     |
	| UCHIJAAAA | baubles                 | 1.5.1                    | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHIJAAAA | jei                     | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                      | extrautils2-1.12-1.6.8.jar                      | None                                     |
	| UCHIJAAAA | flyringbaublemod        | 0.3.0_1.12-306787e       | angelRingToBauble-1.12-0.3.0.46+306787e.jar     | None                                     |
	| UCHIJAAAA | appliedenergistics2     | rv5-stable-3             | appliedenergistics2-rv5-stable-3.jar            | None                                     |
	| UCHIJAAAA | aroma1997core           | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | bte                     | Beta build 1.0.0         | Back-To-Eco-0.5-1.12.1.jar                      | None                                     |
	| UCHIJAAAA | ichunutil               | 7.1.3                    | iChunUtil-1.12.2-7.1.3.jar                      | None                                     |
	| UCHIJAAAA | backtools               | 7.0.0                    | BackTools-1.12.2-7.0.0.jar                      | None                                     |
	| UCHIJAAAA | battletowers            | 1.6.1                    | BattleTowers-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | bhc                     | 1.1.0b                   | baubley-heart-canisters-1.12.2-1.1.0b.jar       | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCHIJAAAA | biomesoplenty           | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar   | None                                     |
	| UCHIJAAAA | blur                    | 1.0.4-14                 | Blur-1.0.4-14.jar                               | None                                     |
	| UCHIJAAAA | botania                 | r1.10-350                | Botania r1.10-350.jar                           | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux            | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore            | 2.3.4                    | BrandonsCore-1.12-2.3.4.134-universal.jar       | None                                     |
	| UCHIJAAAA | chesttransporter        | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCHIJAAAA | cofhcore                | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld               | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | conarm                  | 1.0.2                    | conarm-1.12.2-1.0.2.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | ctm                     | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | draconicevolution       | 2.3.5                    | Draconic-Evolution-1.12-2.3.5.269-universal.jar | None                                     |
	| UCHIJAAAA | zerocore                | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJAAAA | bigreactors             | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar               | None                                     |
	| UCHIJAAAA | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | sonarcore               | 5.0.2                    | sonarcore-1.12.2-5.0.2.jar                      | None                                     |
	| UCHIJAAAA | fluxnetworks            | 3.0.1                    | fluxnetworks-1.12.2-3.0.1.jar                   | None                                     |
	| UCHIJAAAA | natura                  | 1.12-4.3.0.23            | natura-1.12-4.3.0.23.jar                        | None                                     |
	| UCHIJAAAA | forestry                | 5.7.0.214                | forestry_1.12.2-5.7.0.214.jar                   | None                                     |
	| UCHIJAAAA | forgelin                | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCHIJAAAA | nei                     | ${mod_version}           | NotEnoughItems-1.12-2.4.0.231-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ftblib                  | 5.2.0.31                 | FTBLib-5.2.0.31.jar                             | None                                     |
	| UCHIJAAAA | gravestone              | 1.10.0                   | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJAAAA | waila                   | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.11                   | tesla-core-lib-1.12-1.0.11.jar                  | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.5.13-103.jar       | None                                     |
	| UCHIJAAAA | infernalmobs            | 1.7.5                    | InfernalMobs-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks           | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCHIJAAAA | jehc                    | 1.3.1                    | jehc-1.12-1.3.1.jar                             | None                                     |
	| UCHIJAAAA | jeibees                 | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAA | journeymap              | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | jeresources             | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| UCHIJAAAA | lootbags                | 2.5.3b                   | LootBags-1.12.2-2.5.3b.jar                      | None                                     |
	| UCHIJAAAA | magicbees               | 1.0                      | MagicBees-1.12-3.1.7.jar                        | None                                     |
	| UCHIJAAAA | minecolonies            | 1.12.2-0.8.4932          | minecolonies-universal-1.12.2-0.8.4932.jar      | None                                     |
	| UCHIJAAAA | projecte                | 1.12-PE1.3.1B            | ProjectE-1.12-PE1.3.1B.jar                      | None                                     |
	| UCHIJAAAA | moartinkers             | 0.6.0                    | moartinkers-0.6.0.jar                           | None                                     |
	| UCHIJAAAA | netherendingores        | 1.12.2-1.2               | Netherending-Ores-1.12.2-1.2.jar                | None                                     |
	| UCHIJAAAA | orespawn                | 3.2.0                    | OreSpawn-1.12-3.2.0.95.jar                      | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCHIJAAAA | portalgun               | 7.0.0                    | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCHIJAAAA | reccomplex              | 1.4.6                    | RecurrentComplex-1.4.6.jar                      | None                                     |
	| UCHIJAAAA | thermalexpansion        | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | redstonearsenal         | 2.5.1                    | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | rftools                 | 7.14                     | rftools-1.12-7.14.jar                           | None                                     |
	| UCHIJAAAA | roguelike               | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJAAAA | roots                   | 0.104                    | roots-2-0.104.jar                               | None                                     |
	| UCHIJAAAA | shatter                 | 7.0.0                    | Shatter-1.12.2-7.0.1.jar                        | None                                     |
	| UCHIJAAAA | thermaldynamics         | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | tinkersaddons           | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                | None                                     |
	| UCHIJAAAA | tinkertoolleveling      | 1.12-1.0.2b.DEV.1a79301  | TinkerToolLeveling-1.12-1.0.2b.jar              | None                                     |
	| UCHIJAAAA | twilightforest          | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |
	| UCHIJAAAA | wailaharvestability     | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHIJAAAA | wanionlib               | 1.12.2-1.3               | WanionLib-1.12.2-1.3.jar                        | None                                     |
	| UCHIJAAAA | yabba                   | 1.1.2.14                 | YABBA-1.1.2.14.jar                              | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.11                   | tesla-core-lib-1.12-1.0.11.jar                  | None                                     |
	| UCHIJAAAA | unidict                 | 1.12.2-1.8               | UniDict-1.12.2-1.8.jar                          | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2750
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: SuperSimpleCraft 1.12
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 1300X Quad-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 16
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.36
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by iChun** [comment]
Due to suspicions that this crash might be due to optifine, and due to the age of this issue, I am closing this issue. My apologies we weren't able to work out a fix
