### ISSUE TITLE
Crash with Pigs? What?

### ISSUE THREAD

**Issue by Blunder-G** [iChun/Shatter#36]
I'm experiencing this stuff second time.

crash report:
[crash-2021-07-05_00.42.18-client.txt](https://github.com/iChun/Shatter/files/6760650/crash-2021-07-05_00.42.18-client.txt)

log:
[latest.log](https://github.com/iChun/Shatter/files/6760649/latest.log)

**Comment by iChun** [comment]
Fixed in 10.0.1. Sorry for the delay in fixing this!
